### ISSUE TITLE
Questions when following this tutorial

### ISSUE THREAD

**Issue by tingkai-zhang** [sleighzy/k3s-traefik-v2-kubernetes-crd#2]
First of all, thank you so much for creating this tutorial. 

I am able to finish the whole tutorial but I also got a few problems along the way. 

First is that, traefik dashboard does not show anything after I created the ingress route for traefik dashboard and `whoami` app:
 
![image](https://user-images.githubusercontent.com/20318562/93355575-3a527580-f80c-11ea-90c1-8e7f79d8b275.png)

The `whoami` endpoint has not been created.
```
$ kubectl get svc,ep,ingress,ingressroute -o wide
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE   SELECTOR
service/kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   9h    <none>

NAME                   ENDPOINTS              AGE
endpoints/kubernetes   207.244.xxx.xxx:6443   9h

NAME                                      AGE
ingressroute.traefik.containo.us/whoami   13m
```

Second is that, I got `404 page not found` error when testing with `whoami` app. 

How can I debug where could be wrong?  Thank you in advance!

**Comment by sleighzy** [comment]
@tingkai-zhang , thanks, glad you found this helpful so far. I'll have a look and see what I can on my end as well. Which manifest files have you applied for your deployment? Can you confirm that the pod is running for the `whoami` deployment as well. The output of your command indicates that you have an ingressroute for whoami, but I don't see a service listed there. I noticed that I don't have this explicitely in the README file (I can update) but you may need to create the `whoami` service so that the requests can be routed there, and then onto the running pod/container.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: whoami

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami
```

See if applying the above creates the `whoami` service, which then will create the entrypoint, and the Traefik ingressroute should be able to locate the service.

In addition to this are there any errors/warnings in the Traefik pod logs about it not being able to locate this service etc.?

**Comment by sleighzy** [comment]
The Traefik docs for the Kubernetes CRD also show the whoami service in their example https://docs.traefik.io/user-guides/crd-acme/#services, and ingressroutes, if you need more information.

**Comment by sleighzy** [comment]
@tingkai-zhang , I've deployed this and verified that it needs the `Service` applied for the `whoami` deployment for it to show up in Traefik and have requests routed to it as I mentioned earlier. I had the below errors in my Traefik pod logs without that service.

```
time="2020-09-21T07:47:32Z" level=error msg="kubernetes service not found: default/whoami" providerName=kubernetescrd ingress=whoami namespace=default
time="2020-09-21T07:47:34Z" level=error msg="kubernetes service not found: default/whoami" ingress=whoami namespace=default providerName=kubernetescrd
```

The errors went away after I added the service. I've updated the README with the example for the service. I've also added a `100-whoami.yaml` manifest file that can be applied.

Does this help?

**Comment by tingkai-zhang** [comment]
Hello, @sleighzy  Thank you for your reply. I really appreciate you took the time to repro and varied this issue.

What you said makes sense - the error was caused by not deploying the `whoami` service. 
I have been caught up these days but I will try it again on my side and get back to you by tomorrow. 

Thank you and have a great day.

**Comment by tingkai-zhang** [comment]
Hi, I am now able to set it up on my side after following the latest guide.  

Thank you so much for helping me out.
